#!/bin/bash
# Utility script to set one of two different
# environments, either serial or parallel.
#
#

set -e

DOHELP() {

    echo "Usage: $0 [par | serial | summary]"
    echo ""

}

DOSUMMARY() {

    echo "Current Environment: $CUR_ENV"

}



if [ $# -lt 1 ]; then
    DOHELP
    echo ""
    DOSUMMARY
    echo ""
    exit 0
fi

case $1 in
    serial)
        export CUR_ENV "serial"
        sudo cp -v -R /home/${CUSER}/libs/serial/* /usr
        ;;
    par)
        export CUR_ENV "par"
        sudo cp -v -R /home/${CUSER}/libs/par/* /usr
        ;;
    *)
        DOSUMMARY
        exit
        ;;

esac

echo "Setting environment to $1"
echo ""
