# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.ssh.forward_x11 = "true"

  config.vm.define "unicorn-x64" do |v|
    v.vm.provision :shell, :path => "bootstrap_hyrax.sh"
    v.vm.box = "unicorn64"
    v.vm.hostname = "hyrax-server"
  end

end
